export const allUnits = [
  { code: "HNX-01", title: "Anatomy and Physiology" },
  { code: "HNX-02", title: "Medical-Surgical Nursing" },
  { code: "HNX-03", title: "Fundamentals of Nursing & Patient Care" },
  { code: "HNX-04", title: "Pharmacology" },
  { code: "HNX-05", title: "Pediatrics & Neonatal Care (MCH)" },
  { code: "HNX-06", title: "Immunology & Infectious Disease" },
  { code: "HNX-07", title: "Endocrine # MED-SURG" },
  { code: "HNX-08", title: "Neurology # MED-SURG" },
  { code: "HNX-09", title: "Cardiovascular (CVD) # MED-SURG" },
  { code: "HNX-010", title: "Respiratory # MED-SURG" },
  { code: "HNX-011", title: "Gastrointestinal GIT #MED-SURG" },
  { code: "HNX-012", title: "Obstetric" },
  { code: "HNX-013", title: "Genito-Urinary System #MED-SURG" },
  { code: "HNX-014", title: "Hematology & Oncology # MED-SURG" },
  { code: "HNX-015", title: "Orthopedics & Integumentary" },
  { code: "HNX-016", title: "Sensory ENT # MED-SURG" },
  { code: "HNX-017", title: "Gynecology #OBS" },
  { code: "HNX-018", title: "Microbiology" },
  { code: "HNX-019", title: "First Aid, Trauma & Emergency" },
  { code: "HNX-020", title: "Baby at Risk" },
  { code: "HNX-021", title: "Ophthalmology" },
  { code: "HNX-022", title: "Theater Nursing" },
  { code: "HNX-023", title: "Palliative Care" },
  { code: "HNX-024", title: "Intensive Care Unit Nursing" },
  { code: "HNX-025", title: "Dermatology" },
  { code: "HNX-026", title: "Dental, Alimentary, and Biliary Disorders" },
  { code: "HNX-027", title: "Community Health" },
  { code: "HNX-028", title: "Leadership & Management" },
  { code: "HNX-029", title: "Research & Statistics" },
  { code: "HNX-030", title: "Mental Health & Psychiatric Nursing" },
  { code: "HNX-031", title: "Psychiatric & Mental Health Nursing" },
  { code: "HNX-032", title: "Immunization & KEPI" },
  { code: "HNX-033", title: "Nutrition" },
  { code: "HNX-034", title: "Family Planning" },
  { code: "HNX-035", title: "Communicable Diseases & VBD" },
  { code: "HNX-036", title: "HIV & AIDS / STI" },
  { code: "HNX-037", title: "Sociology and Anthropology" },
  { code: "HNX-038", title: "IMNC Peads" },
  { code: "HNX-039", title: "Community Diagnosis" },
  { code: "HNX-040", title: "Primary Healthcare & Community Strategies" },
  { code: "HNX-041", title: "Nursing Ethics & Legal Aspects" },
  { code: "HNX-042", title: "Abnormal Midwifery" },
  { code: "HNX-043", title: "Normal Midwifery" },
  { code: "HNX-044", title: "Special Needs People" },
  { code: "HNX-045", title: "Psychology" },
  { code: "HNX-046", title: "Health System Management" },
  { code: "HNX-047", title: "Teaching Methodology" },
];
